[project]
name = 'Synthetic-Reality-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.reality-nft]
path = 'contracts/reality-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-parameters]
path = 'contracts/reality-parameters.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
